---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bgd
  name: bgd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgd
  strategy: {}
  template:
    metadata:
      labels:
        app: bgd
    spec:
      containers:
      - image: quay.io/csalinas/my-app:4366a43e1732168fb0ea494375dbe9db53b1ae3e@sha256:54cda59e376c701779653614918b16eca98e81888eac49b20b5d9871bf5a7a2c
        name: bgd
        env:
        - name: COLOR
          value: "blue"
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
---
