---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bgd
  name: bgd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgd
  template:
    metadata:
      labels:
        app: bgd
    spec:
      containers:
      - name: bgd
        image: quay.io/csalinas/bgd:1.0.0
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: BG_COLOR
          value: "steelblue"
        - name: MESSAGE
          value: "OpenShift Pipelines+GitOps Demo"
        - name: APP_VERSION
          value: "1.0.0"
        - name: GIT_COMMIT
          value: "1.0.0"
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
---
